### ISSUE TITLE
Ctrl-2,3,4... seems broken in 1.7.1 on Windows?

### ISSUE THREAD

**Issue by khakhalin** [Zettlr/Zettlr#1020]
In the past, Ctrl-2 allowed me to go back to the previously open file. After the 1.7.1. update, it no longer works. Even though this functionality is still described in the docs.

Desired functionality: In the previous version, Ctrl-2 was equivalent to Ctrl-Tab  in most programs, and allowed a user to go to the previously active document. Repeatedly hitting Ctrl-2 allowed a user to switch between 2 notebooks. There was a bug that a newly created notbook wasn't added to the doc queue, but other than this bug, it worked. Now it doesnt.

Similarly, Ctrl-3 was equivalent to Ctrl-(Tab-Tab) of most other programs, and allowed one to cycle through 3 different documents. Also no longer works.

If Ctrl-2 etc are now reserved for some other operation, can we please add Ctrl-Tab, or an other similar shortcut, but the old-school operation?

Platform: Windows 10, Zettrl 1.7.1

**Comment by nathanlesage** [comment]
As already outlined on Twitter, there were breaking changes in 1.7 that we announced in the changelog fairly obvious:

1. `Cmd/Ctrl+[0-9]` do in fact now open tabs, not recent documents
2. `Cmd/Ctrl+Tab` and `Cmd/Ctrl+Shift+Tab` switches back and forth between the tabs

So you can actually get your usecase simply by exchanging the numbers with tabs and shift!

The documentation is outdated, because I have too much to do and couldn't update it correctly as of now

**Comment by khakhalin** [comment]
Thank you! But what is the logic of what gets to be open in a new tab, and what overwrites a tab? I tried to click for a while hoping that I'd get the pattern, but couldn't quite figure it out. And then I re-read (or rather Ctrl-F-ed) through the change log, and couldn't figure it out either. 

Just Ctrl-clicking on a link seems to replace the active document in the current tab, meaning that I don't have a way to go "back". Is there some other combo that always opens stuff in new tabs? Would it be too hard to allow users to switch between two behaviors? Or would it be too hard to emulate a browser, where the default type of click overwrites the current document, but an alternative type of click opens a document "in a new window", and then there's a "back" button?

I'm just looking for a smooth clear workflow that uses both the left menu, and the internal links; that has some logic to it, and facilitates cross-card integration, Zettelkasten-style... Thanks!!

**Comment by nathanlesage** [comment]
> But what is the logic of what gets to be open in a new tab, and what overwrites a tab?

1. If the current, active tab is transient (= italics), it will be replaced by a new file
2. If the current, active tab is intransient (= not in italics; being edited), it will not be replaced, but instead a new tab opens

> Just Ctrl-clicking on a link seems to replace the active document in the current tab

Ctrl+Click is not yet implemented, but I'm well aware that this needs to be the case (or something different)!

**Comment by khakhalin** [comment]
I am still confused about how the tabs work, but imagine the following workflow, for a person that uses Zettlr as a personal Wiki (almost like classic Zettlkasten, except that the majority of cards have somewhat readable ids).

* You create a new entry named "cats"
* You add some tags to this entry, and some "See also" references; say, to the parent `[[animals]]`, and to an adversary `[[dogs]]`.
* Now, once you finished writing about cats, you want to go to both "animals" and "dogs" cards, and cross-reference back. So you Ctrl-Click on "animals", it opens, you edit it. Time to go back. Then you do the same with "dogs".
* Occasionally, while editing a card, you would notice that it references a strange card you forgot about (say, "animals" referencing "Pink Floyd"), and you would visit it, and either just read it, or update it. Which is a normal way of using Zettlkasten, right? Get inspired by being lost in a self-made maze. But from the navigation POV, you now have to navigate from a dead-end card two steps back.

This workflow is also subject to 2 additional requirements:
1. Whatever you do, this navigation via internal links (like `[[Psychodelic]]`) should not be disrupted if you also click on some links in the folder menu on the left. Whatever you do, there should still be an easy way back to the card you edited originally, and you should not have to resort to manual scrolling, or typing "dogs" in the search box.
2. The way you close the window / navigate back shouldn't depend on whether you opened it via internal link, or the folder menu on the left. You cannot expect a person to remember the way a document was opened. It should be self-evident that all documents you're navigating through are ultimately created equal.

Maybe I didn't find a combination of keys, but when I installed 1.7.1, I could not navigate back after Ctrl-clicking on internal links (as Ctrl-2 stopped working), and I could not consistently have them opened in new tabs. Sometimes they somehow appeared in new tabs, but I couldn't find a way to predict this behavior.

(For now I had to downgrade back to 1.6.1, as otherwise my work would have been paralyzed, but I'll be happy to upgrade back and do some testing, if it would be helpful. And if I was just slow-witted, and didn't guess the expected workflow, please tell me what I should have done, and I'll become your most ardent follower once again! I just need some effective keyboard shortcuts, as now, as my Zettelkasten has hundreds of cards, I can no longer rely on manual navigation that was fine early on...) Thank you!!

**Comment by nathanlesage** [comment]
I have just updated the docs to describe how it works: https://docs.zettlr.com/en/core/tabs/

**Comment by khakhalin** [comment]
That's wonderful, thank you!! Very helpful!

But unless I misunderstand it, it still doesn't solve the problem of navigating back, does it? If you click through two `[[internal_links]]`, without editing anything, they both stay transient, which means that they don't produce tabs (as they shouldn't in this case, probably). But there's no "Back button", so you cannot go back from page 2 to page 1. You can only start anew from page 0 that contained the original `[[link]]`... And that would essentially heavily discourage people from cross-linking cards, or idly navigating the cardsniverse, as Luhmann taught us to do...

**Comment by khakhalin** [comment]
And just in case it could be helpful; if I were to imagine an "Ideal" mode, I would have probably proposed something like that (which is essentially Internet Browser-style):

* Clicks in the file list & Ctrl-clicks on `[[internal links]]` overwrite the content of the current tab. The address is also put in the queue for this tab.
* There's a "back" key combo that moves you back. No need to Ctrl-2,3,4 v 1.6.0 complexity; just a simple "back" would be fine. Bonus if it's an easy (left-hand shortcut for a right-handed person) or adjustable shorthand
* Shift-clicks on the file-list & Ctrl-Shift-Clicks on `[[internal links]]` open pages in new tabs. Tabs may be transient or not, it doesn't matter. Each tab has its own queue, so newly open tabs don't get into the parent tab queue, but init their own queue. (Also, it may be Alt-Click and Ctrl-Alt-Click instead of Shift if it's easier, as long as it works with both left and right alts, not just with AltGr).
* There should be a way to cycle through tabs (it may be Ctrl-1,2,3 v 1.7.1 if feels easier, or it maybe Ctrl-Tab if we want to be more similar to other interfaces)

The only two things missing from this list are a "back" button, and perhaps a consistency of "modifier-key clicking".

And also, can we please reopen this issue as a feature request or something?  I find it strange that an issue that makes a newer version of a product unusable as a personal Wiki / Zettelkasten is considered "closed", just because this issue is described in the documentation... Sorry if it sounds harsh and egocentric, I hope it doesn't, and I have no way to tell how many people use Zettlr as Zettelkasten with readable ids. But it does feel like a reasonable workflow for new users; especially converts from other knowledge systems. And right now this workflow seems to be broken.

Thank you so much!!!

**Comment by nathanlesage** [comment]
> Clicks in the file list & Ctrl-clicks on [[internal links]] overwrite the content of the current tab.

Something like that, yes, I intend to add shortcuts to prevent transiency from overwriting tabs!

**Comment by khakhalin** [comment]
I am not sure this is what I described, but again, maybe I still think in a "wrong paradigm" haha :)

Can we please reopen this thread as a feature request, so that other people could chime in if they want to? I thought I could do it from my side, but I don't seem to be able to find a button...

**Comment by nathanlesage** [comment]
Nah, the issue title is not really about this. Please, just give me a few days, I'm completely overwhelmed and there IS functionality still missing which I will patch, but not if I get bombarded with dozens of issues everyday :/ I need a phase of no new issues where I have a chance to clean up everything a little bit.

**Comment by khakhalin** [comment]
Thanks and sorry again! You are still the best! :) And I'm full of hope for the future or ζ !!! :)
