### ISSUE TITLE
Toggling to tree window with shortcut not working

### ISSUE THREAD

**Issue by Blistax** [Zettlr/Zettlr#1352]
## Description

The shortcut for toggling between tree window and editor window (inside note) CTRL+SHIFT+T is not working for my device.
## Reproducing

Pressing CTRL+SHIFT+T
## Expected behaviour

Using this shortcut should toggle between tree window and editor window such that I can browse through my folders with arrow keys.

## Platform
 - OS and version: Windows 10, OS build 19041.508
 - Zettlr Version: 1.7.5

## Additional information

I browsed through the previous issues and this should have been fixed in Zettlr 17.4, but I am using this version already.
Does my input method influence this kind of behaviour?

**Comment by Blistax** [comment]
Update:

Perhaps related to this matter. I am also not able to paste images to the editor simply using CTRL+V.

I am not sure what's going on here.

**Comment by nathanlesage** [comment]
If you want to paste an image, Windows most likely does not insert it into the clipboard. This, however, is currently necessary to trigger the paste-image dialog. Otherwise, the image will be linked only. The rest: I would like to ask you to wait for the beta versions for the next major versions, and test it out there. These will include a full rewrite of the editor itself, so maybe the former works as expected then.

**Comment by Blistax** [comment]
Thanks for the information. Looking forward for the update!

**Comment by nathanlesage** [comment]
Should work now in the 1.8 betas.

**Comment by Blistax** [comment]
I've installed the 1.8.0 beta edition, but unfortunately, it still does not work. I've used the new short cut CTRL+ALT+I now (also tried the CTRL+SHIFT+I, but did not succeed either). Damn you Windows, haha.

**Comment by nathanlesage** [comment]
> I've installed the 1.8.0 beta edition, but unfortunately, it still does not work. I've used the new short cut CTRL+ALT+I now (also tried the CTRL+SHIFT+I, but did not succeed either). Damn you Windows, haha.

The shortcut is Ctrl+Shift+T and that one should work. Ctrl+Alt+I should toggle the devtools or insert an image (one of the two)

**Comment by Blistax** [comment]
Ah, that's stupid of me. Well, I tried this again with CTRL+SHIFT+T with the 1.8.0 beta, however, this is also not working.
