### ISSUE TITLE
reveal.js export not working in 1.8.0.beta

### ISSUE THREAD

**Issue by ritvje** [Zettlr/Zettlr#1385]
## Description

Exporting to reveal.js fails in 1.8.0.beta and when using the `test-gui` on develop branch. 

I got the following in the logging in `test-gui`:

```
[17:42:11] Trying to run command through Application: export
[17:42:11] Running Pandoc with command: pandoc "/tmp/export.tmp" -f markdown -t revealjs      --pdf-engine=xelatex --mathjax -o "/tmp/20201028174025.revealjs"
[17:42:11] Pandoc ran successfully and did not produce any output.
[17:42:11] ENOENT: no such file or directory, open 'path/to/Zettlr/assets/template.revealjs.htm'

```

In addition to this, in 1.8.0.beta also sometimes `[Error] Cannot read property 'toLowerCase' of undefined` happens.

## Reproducing

I used the following file for testing:

```markdown
--- 
title: Reveal.js test
id: 20201028174025
keywords: 
- testing
- reveal.js
...
# This is a presentation for testing reveal.js export

Slide 1
---
Slide 2
```

## Expected behaviour

The markdown file is exported as a html presentation.

## Platform
 - OS and version: Ubuntu 18.04
 - Zettlr Version: 1.8.0.beta

**Comment by nathanlesage** [comment]
> In addition to this, in 1.8.0.beta also sometimes [Error] Cannot read property 'toLowerCase' of undefined happens.

This is fixed on the develop, but I knew the template would cause problems. But I may have an idea of how to fix that.

Thanks for testing out the develop branch, though! It really helps me with enduring the release is bug-free! Your help is very much appreciated!

**Comment by fnw** [comment]
I am on 1.8.0-beta.2 on  Windows 10 and, using ritvje's example (and my own files), I still get this error. The full error log (minus personal information) is as follows:

```
[13:28:30] [Info] Running Pandoc with command: pandoc "path\export.tmp" -f markdown -t revealjs      --pdf-engine=xelatex --mathjax -o "path\presentation.revealjs"
[13:28:32] [Info] Pandoc ran successfully and did not produce any output.
[13:28:32] [Error] ENOENT, assets\template.revealjs.htm not found in "(user folder)\AppData\Local\Programs\Zettlr\resources\app.asar" | Details: {"code":"ENOENT","errno":-2}
```

I know you have indicated that this is fixed on develop, but the release notes of 1.8.0-beta.2 mention a fix for failed reveal.js exports, so I'm letting you know just in case this was unexpected :)

**Comment by nathanlesage** [comment]
There have been two fixes: One with regard to switching to revealJS 4, and the other to making it available after builds. Due to switching to Electron-forge, some stuff did not work out of the box, but I just tested revealJS, it should work now (like, newest develop build, I don't know about the latest released build)

**Comment by jkeiren** [comment]
I am running version 1.8.0 on MacOS, and am still running into the issue above. So it seems the 1.8.0 release still has the issue.

**Comment by nathanlesage** [comment]
Oh for fucks sake, I'm an idiot. The revealJS template is never built during build — no wonder it works locally on my dev machine and fails everywhere else.

Apologies for that rookie mistake!

**Comment by bilalel** [comment]
Hi @nathanlesage ,

Thank you for checking this up.

Does it mean we need to build the revealjs package?
I just installed the app on Windows, version 1.8.0

**Comment by nathanlesage** [comment]
No need to build anything, just wait for next Friday, when I'll release 1.8.1!
