### ISSUE TITLE
Double input enabled randomly

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#222]
I don't know how I does that but it looks like the double caret/input is enable randomly when a type (maybe I lightly touch the touchpad). This is very frustrating as it put the double carret somewhere random and mess with my text.

**Comment by nathanlesage** [comment]
Double input as in the sense of two cursors so that you write doubly? This should normally only happen when you hold the `Option` (or `Alt`) key … could it be that you happen to have a MacBook 2017 (with the light keys) which are known to be stuck at some point due to dirt? At least this is something unnerving me, but it's not something Zettlr could alleviate …

**Comment by ploum** [comment]
yes, this is with the two cursors that write doubly (I never really understood that feature but, as it is in many text editors, I guess it is useful for some usecases).

I have a macbook 2016 but:

1. As far as I can check, my keys are not stuck and work properly.

2. I cannot make the second cursor happen on purpose. I don't really understand what I'm supposed to do. I only know that it happens very frequently when I'm typing.

**Comment by nathanlesage** [comment]
Ah, I think I found it in the manual again:

![grafik](https://user-images.githubusercontent.com/17251683/58785656-36362080-85e6-11e9-8f26-39ec15efbd74.png)

So it's the Command key, maybe macOS maps some clicking-behaviour on the touchpad to this ...? I'm not sure, but it shouldn't happen randomly, that's for sure!

**Comment by ploum** [comment]
Strange, I can't reproduce that. Also, it seems to work only when something is selected (which is not the case when I type, obviously).

Anyway, is there a way for me to disable the feature in Zettlr ?

To be honest, I've found that a lot of the mouse operations are very buggy in Zettlr (like the folders moving then creating artefacts on the screen while I'm juste simply moving the pointer or selections being moved and copied but nothing that I could reproduce clearly). I don't know if it's my computer, MacOS or a general issue with Electron.

**Comment by nathanlesage** [comment]
> To be honest, I've found that a lot of the mouse operations are very buggy in Zettlr

Yeah, I'm getting such reports from other people as well. In one case it seems to have been resolved by clearing the cache (that is, removing everything from the AppData directory except the Zettlr-files, that is the config, stats and tags, iirc). So it indeed seems to be a problem with the Blink cache not working as expected.

Still, it's strange that I don't experience any of the issues that are reported here, because it feels as if my version of Zettlr just mocks me, pretending that there are no problems (which there nonetheless are).

**Comment by nathanlesage** [comment]
Hey @ploum, did this issue resolve already …?

**Comment by ploum** [comment]
Yes. I still have the issue but I have also cursor issues in other apps so it seems something related to macOS. (my father has the same problems on his macbook).

Not zettlr then.

**Comment by nathanlesage** [comment]
Alright, thanks for responding :)

Seems as if Apple wants to go wireless on the input devices as well …
