### ISSUE TITLE
[Bug] Once the "file has been modified on disk" message has appeared the file is sometimes still visible on screen after it has been closed.

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#2511]
### Description

I'm not sure I've figured out exactly what circumstances are necessary to trigger this, so sorry this will be a bit vague.

If I'm editing a file and then the "file modified on disk" message appears, then there is sometimes a visual bug later when I close the tab containing the file.  Sometimes, I don't know what triggers it, the file I just shut is still displayed in the editor window even though the tab header for the file has gone.  As soon as I click on a different tab it vanishes.

I haven't tried editing the non-open file – I didn't to check if I can interact with it till just now, so next time I see this I'll see what happens and report back.

### Reproducing

I haven't got a way to reproduce this, the "file modified on disk" dialog needs to appear first and I don't know how to reproducibly trigger that so I haven't been able to test the later problem.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

Another minor cosmetic bug, but once again confusing so I thought it worth reporting.

**Comment by nathanlesage** [comment]
Alright, feel free to check up again, but this might be a regression from the "jumpy text bug" I've fixed earlier, could that be …?

**Comment by mousetrappling** [comment]
I'm not entirely sure what you mean by "a regression from" but it certainly sounds like the bugs could be related.  Is there going to be a new beta?  Once there is (or 2.0.0 is live) I'll keep an eye out for it happening again.

**Comment by nathanlesage** [comment]
Yes, "regression" generally refers to "is caused by" or something like that; and I thiiiiink that I might have fixed this bug when I fixed the scroll bug.

On Monday, there will be a new nightly, as every week, and some time in the end of next week I plan on having the final beta before 2.0 stable!

**Comment by mousetrappling** [comment]
OK, I'll keep an eye out for it after I get the new beta.

**Comment by mousetrappling** [comment]
Sorry, I completely spaced out on getting back to you on this.

Yes, it still happens and it's still very rare.  I still have no idea what triggers it – I see the "file modified on disk" message very frequently but rarely end up with the file left on screen once I've closed it.  I am 90% certain I've seen it since 2.0.3 was released.

I also tried editing it once, it'll let you edit it but then won't save it (I assume because it's not really open).  If you then open the file it reverts to state on disk (unsurprising), but it has the asterisk in the tab header to show it has unsaved changes (but these no longer exist anywhere).  You can't save it and get rid of the asterisk till you edit it and then save.

I guess it's possible for this to lead to data loss if someone forgets they've shut the file and edits this phantom.

**Comment by nathanlesage** [comment]
Hm. If that happens again, would you mind having a look into the log files to see if some errors are logged? Or even if it's just warnings. That might give me a hint as to what is happening exactly, and help fix this for good!

**Comment by mousetrappling** [comment]
Sure, I'll keep an eye out and look at the logs.  It might take a while, though coz it is a rare occurrence!

**Comment by mousetrappling** [comment]
And having said that, it happened today.  From a glance I'm not sure there's much useful in the logs :(

Log file messages from Zettlr when I had a phantom file displayed after closing it, I copied from a few entries before the event that I think triggered the warning message about file changed on disk:
[11:58:23]	Saving file 20210327222410.md...
[11:58:23]	[WATCHDOG] Emitting event: change:/home/pling/Zettelkasten/Notes/20210327222410.md
[11:58:23]	Updated modtime for fileDescriptor 20210327222410.md to 1639655903677
[11:58:23]	[Stats Provider] Writing statistics to file
[11:58:23]	File 20210327222410.md saved.
[11:58:23]	Updated modtime for fileDescriptor 20210327222410.md to 1639655903677
[11:58:40]	Saving file 20210327222410.md...
[11:58:40]	[WATCHDOG] Emitting event: change:/home/pling/Zettelkasten/Notes/20210327222410.md
[11:58:40]	Updated modtime for fileDescriptor 20210327222410.md to 1639655920381
[11:58:40]	[Document Manager] Emitting remote change event for file /home/pling/Zettelkasten/Notes/20210327222410.md
[11:58:40]	Updated modtime for fileDescriptor 20210327222410.md to 1639655920381
[11:58:40]	[Stats Provider] Writing statistics to file
[11:58:40]	File 20210327222410.md saved.
[11:58:51]	[Config Provider] Writing configuration file to /home/pling/.config/Zettlr/config.json...

I typed some text in the phantom:
[12:00:45]	Error saving file: File to save not found!
[12:00:45]	[R] [Main Window] Retrieved a falsy result from main, indicating an error with saving the file. (index.js:2)

Reopened the file:
[12:06:16]	[Application] Opening file /home/pling/Zettelkasten/Notes/20210327222410.md
[12:06:21]	[Config Provider] Writing configuration file to /home/pling/.config/Zettlr/config.json...

Shut it again, still on screen:
[12:08:07]	[Config Provider] Writing configuration file to /home/pling/.config/Zettlr/config.json...

Can’t think of any other tests to do so clicked on a tab to get the phantom file to go away, no log messages when I did that.

**Comment by mousetrappling** [comment]
And here's a similar section of logs for a file that gave me the file modified on disk message but didn't leave a phantom file behind when I closed the tab.  Again, it doesn't look to me like this tells you anything but maybe it will!

[13:20:34]	Saving file 20200523221306 The Nile is Central to the Development of Egyptian Culture.md...
[13:20:34]	[WATCHDOG] Emitting event: change:/home/pling/Zettelkasten/Notes/20200523221306 The Nile is Central to the Development of Egyptian Culture.md
[13:20:34]	[Document Manager] Emitting remote change event for file /home/pling/Zettelkasten/Notes/20200523221306 The Nile is Central to the Development of Egyptian Culture.md
[13:20:34]	Updated modtime for fileDescriptor 20200523221306 The Nile is Central to the Development of Egyptian Culture.md to 1639660833995
[13:20:34]	Updated modtime for fileDescriptor 20200523221306 The Nile is Central to the Development of Egyptian Culture.md to 1639660833995
[13:20:34]	[Stats Provider] Writing statistics to file
[13:20:34]	File 20200523221306 The Nile is Central to the Development of Egyptian Culture.md saved.
[13:20:36]	[Config Provider] Writing configuration file to /home/pling/.config/Zettlr/config.json...
[13:20:49]	[Config Provider] Writing configuration file to /home/pling/.config/Zettlr/config.json...

**Comment by nathanlesage** [comment]
Hm. If you close that file, do you have other files still open? Or was that the only one and then no more files were open? This could indicate that I made an error that the last file to be closed is not completely removed from the internal state, and so shows up

**Comment by mousetrappling** [comment]
I always have other files open, and actually can't remember the last time I shut every file that's open in Zettlr (I have a dashboard file with useful links to things I'm working on, so that is always open even if I shut everything else down).  I think for that specific file that went wrong I had half a dozen other tabs of open files.  It was neither the most recent nor the longest ago file I'd opened and the tab was somewhere in the middle of the list of tabs.

Another observation I hadn't mentioned above – when I went to re-open the file from the file manager sidebar it was already highlighted as if it was the open file I was looking at.

I've shut Zettlr now, but before I did I copied out everything that was logged during that session so let me know if you want to see that.

**Comment by nathanlesage** [comment]
> when I went to re-open the file from the file manager sidebar it was already highlighted as if it was the open file I was looking at.

Mh, so apparently the file manager AND the editor both thought that the file was still the active one, despite you closing it, right? Hm. Let's wait for 2.1, which also introduces some changes and improvements in how open files are handled, maybe the error is gone in that version!

**Comment by mousetrappling** [comment]
I only used 2.1.0 very briefly this afternoon before I got bitten by #2945 badly enough to revert to 2.0.3.  But in that time I had a file remain hanging about as a phantom.  The logs are as below:

[16:40:34]	Saving file 20200521214953 King Must Be Lord of the _Two_ Lands.md...
[16:40:34]	[WATCHDOG] Emitting event: change:/home/pling/Zettelkasten/Notes/20200521214953 King Must Be Lord of the _Two_ Lands.md
[16:40:34]	Updated modtime for fileDescriptor 20200521214953 King Must Be Lord of the _Two_ Lands.md to 1640796034867
[16:40:34]	[Stats Provider] Writing statistics to file
[16:40:34]	File 20200521214953 King Must Be Lord of the _Two_ Lands.md saved.
[16:40:34]	Updated modtime for fileDescriptor 20200521214953 King Must Be Lord of the _Two_ Lands.md to 1640796034867
[16:40:36]	[R] [Main Window] TypeError: Cannot read properties of undefined (reading 'from') (index.js:2)
[16:40:37]	[R] [Main Window] Uncaught TypeError: Cannot read properties of undefined (reading 'to') (index.js:2)
[16:40:37]	[R] [Main Window] Uncaught TypeError: Cannot read properties of undefined (reading 'to') (index.js:2)
[16:40:37]	[R] [Main Window] Uncaught TypeError: Cannot read properties of undefined (reading 'to') (index.js:2)
[16:40:37]	[R] [Main Window] Uncaught TypeError: Cannot read properties of undefined (reading 'to') (index.js:2)
[16:40:39]	[R] [Main Window] Uncaught TypeError: Cannot read properties of undefined (reading 'to') (index.js:2)
[16:40:42]	[R] [Main Window] Uncaught TypeError: Cannot read properties of undefined (reading 'to') (index.js:2)
[16:40:44]	[R] [Main Window] Uncaught TypeError: Cannot read properties of undefined (reading 'to') (index.js:2)
[16:40:44]	[R] [Main Window] Uncaught TypeError: Cannot read properties of undefined (reading 'to') (index.js:2)
[16:41:20]	[Config Provider] Writing configuration file to /home/pling/.config/Zettlr/config.json...

Not sure if the errors are relevant to this, or were to do with the file having stopped responding: I'd been trying to edit a citation and not only did that not respond but nothing else seemed to respond in that tab.  Shutting the file left a phantom.

**Comment by nathanlesage** [comment]
>  I'd been trying to edit a citation and not only did that not respond but nothing else seemed to respond in that tab. Shutting the file left a phantom.

I think the errors are connected to the file not responding. Don't quite know if they also relate to the phantom file. Maybe it all just resolves once I push the next update. I think the biggest thing was actually that the Vue update broke a few things which I missed in time for 2.1, maybe this will then also resolve.

**Comment by mousetrappling** [comment]
Upgraded to 2.1.1 this morning.

Still get phantom files sometimes on closing a file after seeing the "file changed remotely" dialog.  They behave exactly the same as they were in 2.0.3 and produce the same errors which is no error on file closure, but if you try and edit the phantom it says:

[12:09:17]	Error saving file: File to save not found!
[12:09:17]	[R] [Main Window] Retrieved a falsy result from main, indicating an error with saving the file. (index.js:2)

**Comment by nathanlesage** [comment]
I'm still no smarter about that issue, unfortunately :( And it never happens for me, so I couldn't reproduce this …

**Comment by bilderbuchi** [comment]
> And it never happens for me, so I couldn't reproduce this …

One reliable way for me to trigger these "phantom files" is to 
* have a file with a table
* place the cursor in the table editor
* press Ctrl-W (with our without editing anything)
* observe the closed file, lack of tab bar, and presence of raw markdown (interestingly, only of the table) in the main window.

**Comment by nathanlesage** [comment]
@bilderbuchi That's an interesting observation; I wouldn't have thought about the TableEditor having to do something with this! I will attempt to follow your steps to reproduce this tomorrow.

**Comment by bilderbuchi** [comment]
Could be that it's a red herring, and only _one_ way to trigger the phantom, but maybe fixing one also fixes the other? :D

**Comment by mousetrappling** [comment]
It must be only _one_ way to trigger it, as I never use the table editor.  But I've still got no idea why the ones I've seen are triggered, so lets hope that it all has the same root cause!

**Comment by nathanlesage** [comment]
Yeah, let's hope … I've today begun sifting over the TableEditor and refactoring the thing, maybe while doing so I remove bugs as I go. I have found that often when you revisit older code with new knowledge, you almost automatically just write better and more bug-free code. Similar to those weird phantom documents.

Out very last hope would be the migration to CodeMirror 6 sometime this year!

**Comment by mousetrappling** [comment]
Since I stopped seeing the file modified on disk dialog messages (by switching on the watchdog polling setting) I haven't seen a single phantom file.  So it definitely has to do with those messages, but now I'm not much use for helping to troubleshoot!

**Comment by nathanlesage** [comment]
Ahhh, that would mean that the bug occurs when the dialog message is being shown that a remote file is modified! I'll trigger that sometime this week and see where the error happens! That's already a great help :)

**Comment by nathanlesage** [comment]
This should've now been fixed. If not, please comment.
