### ISSUE TITLE
[Bug] After installing or upgrading to Zettlr-2.1.2-x64 a get a blank screen when starting Zettlr

### ISSUE THREAD

**Issue by joep1977** [Zettlr/Zettlr#3043]
### Description

After upgrading to Zettlr 2.1.2 I get a blank screen when starting Zettlr. No functionality, no options. The only thing I can do is shut down the app. 

### Reproducing

First, I tried to upgrade Zettlr in the normal way. After an error - I don't remember what is said - I tried to install the 2.1.2 version. After opening Zettlr a blank screen with no options.

Second, I tried to uninstall Zettlr and do a new, clean install of 2.1.2. Again, I get a blank screen.

Finally, I deinstalled Zettlr and installed 2.1.1 again and it works like a charm.

### Zettlr Version

Stable (most recent version)

### Specify version

Zettlr-2.1.2-x64

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
> After an error - I don't remember what is said - I tried to install the 2.1.2 version. After opening Zettlr a blank screen with no options.

Would you mind trying to get the error again and make a screenshot of it so we can have a look?

Furthermore, what would also help really really much would be if you could (in your working 2.1.1 setup) activate the debug mode, and then, when you are presented with the blank screen, it should be possible for you to press `Ctrl+Alt+I`. In the opening developer console there will be some errors logged in red. It would help a lot if we could get a screenshot of these as well.

**Comment by joep1977** [comment]
Now I am running 2.1.1. At startup I am told an update is available to 2.1.2. After downloading I press install and than this is the error I get.  Translated from Dutch it says: "This file is currently used by another program." So, upgrading doesn't like this. 

Upgrading does work when I download the 2.1.2 file and install it. However, when opening Zettlr I get a full blank screen; no errors, just blank screen.
![Schermafbeelding 2022-01-15 132551](https://user-images.githubusercontent.com/96820649/149621847-d6a0eb21-ea4d-4a84-9c72-ebc7991db255.png)
![Schermafbeelding 2022-01-15 132551](https://user-images.githubusercontent.com/96820649/149621853-3e80bf1d-27e2-414e-b785-80262b83fb49.png)

**Comment by nathanlesage** [comment]
Ah yeah, this error is an inconvenience I don't know where it comes from, but nothing completely deal breaking. However with regard to the blank screen, it would help a lot if you could follow my steps to open the developer console as soon as you see the blank screen so I can have a look at the errors which are logged there!

**Comment by joep1977** [comment]
Is this what you're looking for?
![Schermafbeelding 2022-01-15 153605](https://user-images.githubusercontent.com/96820649/149625653-7a261306-0f5f-43ea-9453-ae464c0658b7.png)

**Comment by ivmerk** [comment]
At MacOs by arm64 also - After upgrading to Zettlr 2.1.2 getting a blank screen when starting Zettlr.

**Comment by nathanlesage** [comment]
Yes, that was what I was looking for. Mh, could be that something in the config had a hiccup. Did you happen to upgrade from an older version like 1.8?

In any case, does [resetting the app](https://docs.zettlr.com/en/troubleshooting/#3-try-resetting-the-app) mitigate this problem?

**Comment by ivmerk** [comment]
Reseting the app not helped. 
2.1.1 is working OK.

**Comment by alexei271828** [comment]
The same issue with Mac OS Catalina x64 after upgrade from 2.1.1 to 2.1.2. I had to switch back to 2.1.1, everything is OK with 2.1.1.

**Comment by hegedusbela** [comment]
The same issue with KDE Neon 5.23 (Ubuntu 20.04) after upgrade. If I switch back to 2.1.1, everything is OK again. I have tried to reset the app, too. Btw: thanks for the software and the work in it!

**Comment by nathanlesage** [comment]
I think something went wrong in 2.1.2, will release 2.1.3 soon which hopefully fixes this! Please then comment here if it works or still doesn't work!

**Comment by nathanlesage** [comment]
Hey people, would you mind trying the most recent nightly? It is basically the upcoming 2.1.3, but I want to make sure it works for you as well before actually releasing it!

https://nightly.zettlr.com/

**Comment by joep1977** [comment]
Hello Nathan,

Thank you for your effort and commitment - it's very much appreciated, I love your work!

Unfortunately, the nightly build doesn't work. I still get a full white screen. 

Best regards,
Jeroen

**Comment by nathanlesage** [comment]
@kyaso Would you mind also maybe having a look at this issue? I can't reproduce this no matter what I try. I'm going to test this out on my Windows PC later today, but more eyes possibly see more … what irritates me is that those errors seem to indicate that some modules haven't been correctly compiled which seems very unlikely!

**Comment by kyaso** [comment]
@hegedusbela Are you using the AppImage, or the Debian package? I'm using the 2.1.2 AppImage on Manjaro, and having no issues. Would you mind trying out the AppImage (under [Releases](https://github.com/Zettlr/Zettlr/releases/tag/v2.1.2))?

**Comment by kyaso** [comment]
So I dusted off my Windows partition, and tested a bit. I still had some 1.8.x installed, so I uninstalled that first (didn't clean my config). Next, I downloaded and installed 2.1.2. 

When started Zettlr afterwards, I also got the blank screen.

Then, I downloaded and installed 2.1.1 (without uninstalling 2.1.2 first). This time, Zettlr booted without any issue.

Then, again installed 2.1.2 (again, without uninstalling 2.1.1). Now comes the weird part: When I then started Zettlr, I no more got a blank screen....!??

I even repeated the last two steps (2.1.1 - 2.1.2 upgrade-downgrade cycle) multiple times; same result: no blank screen.

**Comment by hegedusbela** [comment]
> @hegedusbela Are you using the AppImage, or the Debian package? I'm using the 2.1.2 AppImage on Manjaro, and having no issues. Would you mind trying out the AppImage (under [Releases](https://github.com/Zettlr/Zettlr/releases/tag/v2.1.2))?

Hi, I have tried the AppImage, too. The same issue, only a blank screen. :-(

**Comment by nathanlesage** [comment]
> I even repeated the last two steps (2.1.1 - 2.1.2 upgrade-downgrade cycle) multiple times; same result: no blank screen.

So … it's … reproducible? If so, would you mind running Zettlr 2.1.2 until it shows you a blank error, then `git checkout` at the TAG of the 2.1.2, run `yarn install --frozen-lockfile` and finally run `yarn start`? I think it might be some issue with the configuration that is causing this, and `yarn start` will run it using the main config, so the only change you should see would be that you get actual files and line numbers in the error messages so that we can find out which function is malfunctioning there

**Comment by kyaso** [comment]
> > I even repeated the last two steps (2.1.1 - 2.1.2 upgrade-downgrade cycle) multiple times; same result: no blank screen.
>
> So … it's … reproducible?

Sorry, I might have been unclear there. I only got the blank screen once when I installed 2.1.2 for the first time. After that, I couldn't reproduce the error anymore, no matter how many times I uninstalled and reinstalled.

But I will keep testing, and when I get that error again, I will try your suggested steps!

**Comment by nathanlesage** [comment]
Ah, I see! Very suspicious …

**Comment by nathanlesage** [comment]
Would everyone who has had those problems in 2.1.2 try to update to 2.1.3? I have fixed a pretty rare but serious issue that affected specifically Windows, and my hope is that this additionally fixed this issue as well!

This bug is now high-priority, so all info that can help fix it is well appreciated!

**Comment by joep1977** [comment]
Hello Nathan,

I am so sorry but the problem persists. First I upgraded from 2.1.1 to 2.1.3...same problem. Then I uninstalled Zettlr completely and installed 2.1.3 from scratch...same problem. Then I re-installed 2.1.1 and it works like a charm. 

Best regards,
Jeroen

**Comment by hegedusbela** [comment]
I am very sorry, but I continue to have the same problem as well. The 2.1.1 works.
Thank you,
hb

**Comment by nathanlesage** [comment]
And the error in the console is still the same as this one? https://github.com/Zettlr/Zettlr/issues/3043#issuecomment-1013692662

If so, would someone mind to click on that very first `index.js:2`, make the dev tools somewhat larger and give me a screenshot of that line of code that opens? It won't be very readable but maybe I recognize the faulty code.

**Comment by nathanlesage** [comment]
I have now investigated that issue a little bit. I was able to produce the same error by forcefully preventing the configuration provider from being loaded in the windows (basically the only instance that has a `get` method). However, I am still unable to reproduce this without forcefully breaking things – both on macOS and on Windows.

That being said: I think the bug is being triggered by certain contexts, and I would suspect that it could be something related to your specific configuration. It might be a wrong setting that accidentally got into the configuration, or some path is causing issues.

Furthermore, I just checked the stack trace from the error message.

* `Object.76250` is the `index.ts` for the main window (makes sense, since the error occurs before the App can be displayed)
* `Module.99293` is possibly the main application's render function (coming from Vue.js)
* `Module.11283` is some intermediary module that I couldn't really identify
* `Object.66844` is the main `App.vue` instance (i.e. the object holding the configuration of the App component)
* Finally, `Module.77783` neither exists on v2.1.1 nor on v2.1.3. I've checked out to v2.1.2 and I found it: It's the `AutocompleteText.vue` component.

There are in fact two calls to `global.config.get`, but none of them occur in a context where `global.config` could be `undefined`.

Additionally, there were no changes to the `AutocompleteText.vue` component between v2.1.1 and v2.1.2 as the commit history shows: https://github.com/Zettlr/Zettlr/compare/v2.1.1...v2.1.2

***

Taking all of this into account, would you who experience this problem (@joep1977, @hegedusbela, @alexei271828 and @ivmerk) go into the directory which the [documentation on Troubleshooting](https://docs.zettlr.com/en/troubleshooting/#3-try-resetting-the-app) mentions and **only rename `config.json` to `config.json.backup` as well as completely remove the fsal-folder** and then run v2.1.3 (without starting v2.1.1 again prior to that)?

The directory is: `C:\Users\<your username>\AppData\Roaming\Zettlr` or `/Users/<your username>/Library/Application Support/Zettlr` or `/home/<your username>/.config/Zettlr` depending on your operating system.

Doing so will basically reset Zettlr to a sane default configuration and should fix that issue.

**If it does, it would be tremendously helpful if any one of you (the more the merrier) would share their old config.json (i.e. the config.json.backup) so that I can see what caused this problem!** If you are worried sharing it here online, you can also mail it directly to me at hendrik@zettlr.com.

**Comment by hegedusbela** [comment]
I noticed a very strange thing. I did everything you wrote, installed 2.1.3. When I launched it, the blank screen appeared again. Then I checked the new config.json file. I saw that it takes the language setting from the operating system language (for me: hu-HU). On a sudden idea I changed this to en-UK, saved it and started Zettlr again. It works perfectly! If I change the language back to Hungarian within Zettlr, it starts up with a blank screen again. If I change it again in config.json to en-UK, it works again! It seems that the problem is somewhere here, but I don't know how to do it! Anyway, Zettlr fortunately now works in English for me. Thank you!

**Comment by nathanlesage** [comment]
Oh, alright. Then the issue should be in the language checker. I've implemented some functionality that looks at the system locale and attempts to use that as a language if possible, with a fallback to en-US. So apparently I made a bug there!

That reminds me that I didn't implement tests for that logic … 👀

**Comment by hegedusbela** [comment]
Btw. this doesn't seem like a big problem! The point is that it will be solved. We owe you thanks for writing and making a program that is perfect for humanities people as well.
b.

**Comment by nathanlesage** [comment]
> Btw. this doesn't seem like a big problem!

Well, I would count "there's a blank screen!" as a big problem :D But I'm glad that you had this genius idea that these two things could be related!

I'll be searching for the problem in the next days, then it would be great if I could count on your help for seeing if I actually fixed the bug, I'll get back to you :)

**Comment by nathanlesage** [comment]
FOUND IT!

![image](https://user-images.githubusercontent.com/17251683/152305716-0a49936c-c001-4b4d-b775-824f020d5778.png)

(What is this? Basically: I moved a variable from within the global search out of the component. That looks perfectly innocent which is why I did that in the first place, and I have done so before. The main problem with that is that this code will be immediately executed once the module is _imported_. And modules are imported before another function runs, namely `windowRegister`, which will register a few API calls which `trans` needs, and trans is called in that `contextMenu` variable. @kyaso this info might be interesting for you as well, it's a super difficult to spot bug because of the side effects)

**Comment by kyaso** [comment]
Nice!!

And thanks for sharing that info, didn't know that.

**Comment by nathanlesage** [comment]
> And thanks for sharing that info, didn't know that.

Yeah, that's a super ugly side effect that I also stumbled upon while rewriting the whole main process, and I have yet to find a good way of solving that problem :/

**Comment by nathanlesage** [comment]
Please feel free to test out next Monday's nightly and report back if this fix did not somehow fix the issue!

**Comment by nathanlesage** [comment]
The new nightly is now out: https://nightly.zettlr.com/

Please feel free to test it out to see if the blank screen remains or if it goes away! If there are new issues arising, feel free to open new issues if these haven't yet been reported!

**Comment by emetselaar** [comment]
For me this version also solved the blank screen problem (using win 11). Thanks @nathanlesage

**Comment by hegedusbela** [comment]
Sorry, I just had time to try 2.2.1 for the first time. It works perfectly! Thanks for your work!
I have an important question about citeproc. Sorry, I'm not familiar with it, can I write directly to you or do I have to open a new topic here?

**Comment by nathanlesage** [comment]
@hegedusbela please open an issue and don't write a PM. Not because I don't like chatting with people bilaterally, but rather because otherwise I'd drown in work!

If you're not sure whether what you experience is already a bug, a new discussion would be appropriate!
