### ISSUE TITLE
[Bug] Internal links in lists or with no space afterwards are not formatted correctly on export.

### ISSUE THREAD

**Issue by lecramed0** [Zettlr/Zettlr#3171]
### Description

Thanks very much for Zettlr!

If I place internal links in valid markdown lists (bulleted or numbered) they are not correctly formatted on export. Similarly, if I have a period directly after a link. For example, the following:

```
Main note text.

A link to a local file [[test-note-1]].

A bulleted list including internal links:

- This is text both before and after [[test-note-2]] this note.
- [[test-note-3]]

```

Produces this on export when set to "unlink internal links" (note the trailing brackets on the first link and the remaining brackets in the list):

```
Main note text.

A link to a local file test-note-1]].

A bulleted list including internal links:

    This is text both before and after [[test-note-2]] this note.
    [[test-note-3]]

```

*Note: the bullets are produced as expected, they just don't show up when pasted here.*

Exporting when set to "remove internal links completely" produces this (note that the period is also removed):

```
Main note text.

A link to a local file

A bulleted list including internal links:

    This is text both before and after [[test-note-2]] this note.
    [[test-note-3]]

```

I tried solving this by placing a return between the list items and adding an extra space before the period, like so:

```
Main note text.

A link to a local file [[test-note-1]] .

A bulleted list including internal links:

- This is text both before and after [[test-note-2]] this note.

- [[test-note-3]]

```

The results are not good, but perhaps instructive:

```
Main note text.

A link to a local file .

A bulleted list including internal links:

    This is text both before and after this note.
    

```

### Reproducing

Make a note with valid internal links like in the first code block shown above. Expected behaviour is that they are all un-linked or removed in the same way on export, and the list is not broken.

Tested html and pdf export with the same results.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Yeah, internal links rely on a Lua filter and that can definitely take some more love as your example here shows!

**Comment by nathanlesage** [comment]
I have fixed this filter some time last year, I just forgot to close this issue!

**Comment by niklasliebig** [comment]
I still have this problem in Zettlr 3.0.5 even when it is marked as closed. I have enabled the "Unlink internal links" option and am trying to export something like:
[[file1.md]], [[file2.md]], [[file3.md]]

when exporting to html I get something like:
file1.md]], file2.md]], file3.md
