### ISSUE TITLE
[Bug] v 2.2.1 crashes on start

### ISSUE THREAD

**Issue by wilkohardenberg** [Zettlr/Zettlr#3202]
### Description

Right after installation 2.2.1 crashes on start with the following message "Could not start R: Cannot read properties of undefined (reading 'startsWith')"

![Screenshot 2022-02-14 at 22 33 46](https://user-images.githubusercontent.com/1612993/153950505-cd9f9a37-7094-43dc-9f37-ed07537b93d0.png)

### Reproducing

The point is I don't know if this happens only to me. In any case I only installed the new version and since then, on starting Zettlr it crashes.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.1

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Mojave 10.14.6

**Comment by nathanlesage** [comment]
Would you mind trying today's nightly? I accidentally introduced a few minor bugs during startup, but I have thus far already patched at least one of them -- maybe that already includes the bug you experience!

**Comment by wilkohardenberg** [comment]
Running the nightly does not solve the issue (Zettlr still crashes on me), but it changed the error. Now it reads “Could not start FSAL: Cannot read properties of undefined (reading 'startsWith’)”

**Comment by nathanlesage** [comment]
Ah perfect, now we at least know where the error comes from! That's progress! :D I'll look into it!

**Comment by va-1984** [comment]
hi, I am running 2.2.1 on two ARM Macs, both of which have the Monterey 12.3 Beta (21E5206e).

On one, Zettlr opens and works flawlessly. 
On the other, I get this message on start:

<img width="397" alt="Screen Shot 2022-02-15 at 13 34 08" src="https://user-images.githubusercontent.com/98712866/154127152-eb6f3a5a-e1b9-47d2-85fa-1707e38cd37a.png">

I haven't tried the nightly build yet. 
BTW I _love_ the new features and I'm gonna start supporting Z on Patreon because it's just so good.

**Comment by nathanlesage** [comment]
@va-1984 The bug you are encountering is fixed in the current nightly (the other one not, unfortunately)

**Comment by wilkohardenberg** [comment]
oh, I was hoping 2.2.3 had solved this issue, but I'm still getting the same error: “Could not start FSAL: Cannot read properties of undefined (reading 'startsWith’)” :-( Seems that I have to go back to 2.1.3. for another while.

**Comment by nathanlesage** [comment]
> oh, I was hoping 2.2.3 had solved this issue, but I'm still getting the same error: “Could not start FSAL: Cannot read properties of undefined (reading 'startsWith’)” :-( Seems that I have to go back to 2.1.3. for another while.

Is there already a report for that specific error message out? If so, perfect, if not, please open it. I'm going to close this specific error because it has been fixed by 2.2.3
