### ISSUE TITLE
[Bug] Image displays blurry

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3326]
### Description

Zettlr renders images blurry when displayed at reduced size.

![zettlr_bugreport_blurry](https://user-images.githubusercontent.com/62036826/158617988-7d001aec-3f13-4113-a880-0eaf7c8a80e2.png)

In this screenshot, I have opened the embedded image with windows photo viewer. As you can see, the display in Zettlr on the right is blurry.

The image quality is fine, if Zettlr is used fullscreen, where no downscaled display of images takes place.

### Reproducing

Add image to file and resize Zettlr window. The image in Zettlr gets comparably more blurry than if displayed at the same size in another image viewer.

### Zettlr Version

Nightly

### Specify version

2.2.4

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
There's a chance that this is a Chromium bug. I will check, but it is not unheard of that secondary screens cause problems on all operating systems, especially if they have a different resolution. Maybe the problem could get fixed by opening a different file and then switching back …?

**Comment by leo-hstone** [comment]
Unfortunately this does not help. Restart of Zettlr (starting with the same windows dimensions) does not fix it either.

Thanks for investigating :) As its far away from a real problem this can have low priority.

**Comment by nathanlesage** [comment]
I'm going to close this issue, as it is anyways possibly just an interaction within the downscaling library of Chromium and as such out of my reach in any case.
