### ISSUE TITLE
BUG: When copying a table not all content is copied

### ISSUE THREAD

**Issue by TraceyC77** [Zettlr/Zettlr#3486]
### Description

When trying to copy and paste a table, not all content is copied, so it does not appear in the paste

I took a look at issue 632, but I thought this deserved an issue of it's own.
I'm happy to provide more information or troubleshooting.

### Reproducing

Create a table, for example:

```
| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| Thing 1  | Thing 2  | Thing 3  |
| Row 2 1  | Row 2 2  |    Row 2 3      |
```

Copy the table and paste somewhere else in the document (or anywhere else).
When I copy the example table from Zettlr and paste it *here* I see:

```
| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| Thing 1  | Thing 2  | Thing 3  |
| Row 2 1  | Row 2 2  |          |
```

Note that the last cell was not copied. I see in my clipboard that the cell is missing, so it included during copy.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.6

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Solus

**Comment by nathanlesage** [comment]
Would you mind confirming the following:

* Do everything as you did it with how you found the bug
* Then, before trying to copy the table, click inside a DIFFERENT table cell after you finished writing
* Then, try again.

I suspect this may be related to another bug that I fixed by preventing the table from arbitrarily overwriting contents upon user action

**Comment by TraceyC77** [comment]
Hi,

I tested as you asked, clicking inside a different table cell, then trying to copy & paste. This did not change the last cell being ommited from the copy.

To be clear, I'm using the mouse to drag from before to after the table and then pressing Ctrl-C

I found that if I have two tables in the same document, I can copy the full content for the first but not the second.

In a note where I have two tables, and other content:
If I copy the first table, all table content is copied
If I copy the second table, even with surrounding non-table content, the last cell is missing from the copy.

**Comment by nathanlesage** [comment]
Okay6, this sounds weird. Do you manage to get everything if you deliberately select too much text even after the table ends?

**Comment by TraceyC77** [comment]
While testing that, I came across something reproducible, related to what you're asking that seems to shed some light on the behavior.

## Steps:
Created a note with a heading and some text
After the text, created a table 3 x 3
Added text and a code fence after the table
Filled in the table cells, did *not* create new row (so all existing cells were filled)

Copied stuff before table, table, after table - last cell is not copied
Interestingly, I saved the file and looked at the contents on disk with 'more'. The last cell was not saved.
(See screenshot zettlr_note_on_disk.png)

Went back to the table, inserted a new row (table was now 3 x 4)
Remove the new row (table is once again 3 x 3)
Copy same stuff - all cells in 3x3 table are copied


## Related
There's a related bug, that seems to point to the same root cause.
Sometimes if I copy text before the table, the table and after the table, when I paste that the table is in raw ascii, the formatting code doesn't trigger. (see screenshot zettlr_paste_table1.png). Aside, it doesn't matter if the code fence is included in the copy / paste or not.

**Comment by nathanlesage** [comment]
Alright, thank you very much for checking this! It looks like the table selection code is off... might take some time to reliably track this down!

**Comment by nathanlesage** [comment]
Cannot reproduce this anymore, probably fixed with the large changes last year – closing as fixed.

**Comment by TraceyC77** [comment]
I can still reproduce the reported issue with 2.3.0. What version did you test with? It's possible the issue is fixed in a version greater than what I'm running.

If I copy this:
```markdown
new stuff

| head 1 | head 2 | head 3 |
|--------|--------|--------|
| 1      | 2      | 3      |
| 4      | 5      | 6      |

blah blah

more stuff

```

After pasting it, the number 6 in the last cell is missing. All other text is pasted correctly. In fact, if I copy it and paste it here, it shows the same thing.

```markdown
blah blah

new stuff

| head 1 | head 2 | head 3 |
|--------|--------|--------|
| 1      | 2      | 3      |
| 4      | 5      |        |

blah blah

more stuff
```

**Comment by Lollixzc** [comment]
> I can still reproduce the reported issue with 2.3.0. What version did you test with? It's possible the issue is fixed in a version greater than what I'm running.
> 
> If I copy this:
> 
> ```gfm
> new stuff
> 
> | head 1 | head 2 | head 3 |
> |--------|--------|--------|
> | 1      | 2      | 3      |
> | 4      | 5      | 6      |
> 
> blah blah
> 
> more stuff
> ```
> 
> After pasting it, the number 6 in the last cell is missing. All other text is pasted correctly. In fact, if I copy it and paste it here, it shows the same thing.
> 
> ```gfm
> blah blah
> 
> new stuff
> 
> | head 1 | head 2 | head 3 |
> |--------|--------|--------|
> | 1      | 2      | 3      |
> | 4      | 5      |        |
> 
> blah blah
> 
> more stuff
> ```

There is a new 3.0.0 version which is in beta. You can find nightlies [here](https://nightly.zettlr.com/) or a beta in the releases page.

**Comment by nathanlesage** [comment]
> What version did you test with?

As @Lollixzc mentioned, I always attempt to reproduce these things with the most recent state of the develop branch, and if it's fixed there, I regard it as fixed. We are just right now in this situation where many bugs of 2.3 are fixed, but the next version is still some time ahead.

But the nightlies and betas are already much more stable than 2.3; the only reason I don't yet release a new one is because I want to exterminate all open bugs before release.
