### ISSUE TITLE
[BUG] RegExp-Search Fails if Regular Expression Contains a Forward-Slash

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#353]
## Description

When performing a regular-expression-search with an expression that contains a slash, the app will treat everything behind that slash as belonging to the supplied flags.

## Reproducing

Perform a regular expression search with the expression `/<a href="(.+?)">(.+?)<\/a>/`. The `a>` will be treated as if they were flags which normally occur behind the last slash.

## Expected behaviour

Do not treat slashes inline as delimiters, only the last slash should be treated that way.

**Screenshots**

## Platform
 - OS: [e.g. iOS] any
 - OS Version [e.g. 11] any
 - Zettlr Version [e.g. 0.15] any > 1.4
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information

Culprit lines:

https://github.com/Zettlr/Zettlr/blob/9778467c3130961ba897f0d9d252b21cc40a348f/source/common/util/make-search-regex.js#L30-L33

Needs to be changed to divide the string on the last occuring slash, otherwise multiple slashes will result in an array containing more than two indices. Alleviation by the following code:

```javascript
// The user wants to do a regex search -> transform
let r = term.split('/') // 0 is empty, the last index contains the flags, the expression is everything else.
r.shift() // Remove empty index 0
re.flags = r.pop().split('').concat(injectFlags) // Retrieve the flags, convert to char array and concat
re.term = r.join('/') // Reassemble the expression if it contained forward-slashes.
```

**Comment by nathanlesage** [comment]
Fixed

**Comment by ashprice** [comment]
I still cannot search for forward slashes using regex.

Say I am searching for a common string in the docs; `Cmd/Ctrl' - if I am not mistaken, the correct regex would be /Cmd\/Ctrl/g. As soon as the </> is entered, the search runs. I have tried playing with the 'flavour' of regex, trying things like eg. /Cmd\\\/Ctrl/ to no results. 

Thank you for your patience, and sorry for flooding you with notifications.

**Comment by nathanlesage** [comment]
> I still cannot search for forward slashes using regex.

I close issues as soon as the fix is in the repository, not when a release is issued, to keep the issue list clean. It will be fixed with the upcoming 1.4.3. This way you know that each closed issue **will** with certainty be fixed in the next release to be issued.

**Comment by ashprice** [comment]
Thanks for the clarifications and fast responses. I've not worked on any projects with a release cycle, so I didn't realise that was the likely explanation. Have a good day.
