### ISSUE TITLE
Proxy for LanguageTool

### ISSUE THREAD

**Issue by UFOMelkor** [Zettlr/Zettlr#4084]
### Description

I tried the latest beta to enjoy the LanguageTool support. At home, it works really nice (once I've configured it correctly), but at work the only response that is shown in the toolbar is *LanguageTool: [warning sign] (offline)*. 

I guess the reason – as the used credentials are the same – is the proxy, which is required at work. The system environment variables (http_proxy, https_proxy, no_proxy) are all set.

Another obstacle I stumbled upon is the configuration. I have an account for LanguageTool and I entered the credentials without setting the server. This results in a *404* error. It took a moment to understand that I needed to enter `https://api.languagetoolplus.com` as server. Perhaps it might be better to automatically use this as server if no server is given and credentials are used because languagetool.org seems to error otherwise.

### Proposed Changes

Add a configuration for a proxy or (better) read the system proxy and apply him.

### Caveats

I don't know any

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 22.04

**Comment by nathanlesage** [comment]
> I guess the reason – as the used credentials are the same – is the proxy, which is required at work. The system environment variables (http_proxy, https_proxy, no_proxy) are all set.

I did not meddle with how Zettlr utilizes proxies; however, it may be that Electron, by default, does not utilize the system proxy. I just noticed that I accidentally forgot to log every error, which I fixed in the attached commit.

So in order to find the real reason for the “offline” notification, please wait for the next nightly and/or beta and then, once it fails, have a look into the logs. There should be an error logged that exactly describes what went wrong.

***

Now to your second point. I did not realize that LanguageTool is offering TWO servers, one at https://api.languagetool.org and one at https://api.languagetoolplus.org. The “official” server Zettlr uses is the first one, but if I understand you correctly, credentials only work with the second one. Could you please confirm this?

If so, then maybe the first server is just a legacy one, and the correct one we should be using is the second one. It would be a simple change, once we can confirm that we can indeed redirect everything to the plus-API.

Do you know anything about this? Otherwise, I'd double-check with them first. I really don't want to offer two official servers if possible, since this may confuse people.

**Comment by UFOMelkor** [comment]
> please wait for the next nightly and/or beta and then, once it fails, have a look into the logs

:+1: 

---

Unfortunately, I do not know more about the different APIs. https://api.languagetoolplus.com is the one which is referenced in their [swagger docs](https://languagetool.org/http-api/languagetool-swagger.json)

I've tried different requests with curl:

**With username and apiKey, languagetoolplus.com**  :heavy_check_mark: 

`curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' -d "text=This%20is%20an%20house" -d "language=en-US" -d"username=xxx&apiKey=xxx" "https://api.languagetoolplus.com/v2/check"`

```json
{"software":{"name":"LanguageTool","version":"6.1-SNAPSHOT","buildDate":"2023-01-17 11:23:49 +0000","apiVersion":1,"premium":true,"status":""},"warnings":{"incompleteResults":false},"language":{"name":"English (US)","code":"en-US","detectedLanguage":{"name":"English (US)","code":"en-US","confidence":0.528,"source":"ngram"}},"matches":[{"message":"Use “a” instead of ‘an’ if the following word doesn’t start with a vowel sound, e.g. ‘a sentence’, ‘a university’.","shortMessage":"Wrong article","replacements":[{"value":"a"}],"offset":8,"length":2,"context":{"text":"This is an house","offset":8,"length":2},"sentence":"This is an house","type":{"typeName":"Other"},"rule":{"id":"EN_A_VS_AN","description":"Use of 'a' vs. 'an'","issueType":"misspelling","urls":[{"value":"https://languagetool.org/insights/post/indefinite-articles/"}],"category":{"id":"MISC","name":"Miscellaneous"},"isPremium":false},"ignoreForIncompleteSentence":false,"contextForSureMatch":1}],"sentenceRanges":[[0,16]]}
```

**Without user and apiKey, languagetoolplus.com** :heavy_check_mark: 

`curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' -d "text=This%20is%20an%20house" -d "language=en-US" "https://api.languagetoolplus.com/v2/check"`

```json
{"software":{"name":"LanguageTool","version":"6.1-SNAPSHOT","buildDate":"2023-01-17 11:23:49 +0000","apiVersion":1,"premium":true,"premiumHint":"You might be missing errors only the Premium version can find. Contact us at support<at>languagetoolplus.com.","status":""},"warnings":{"incompleteResults":false},"language":{"name":"English (US)","code":"en-US","detectedLanguage":{"name":"English (US)","code":"en-US","confidence":0.528,"source":"ngram"}},"matches":[{"message":"Use “a” instead of ‘an’ if the following word doesn’t start with a vowel sound, e.g. ‘a sentence’, ‘a university’.","shortMessage":"Wrong article","replacements":[{"value":"a"}],"offset":8,"length":2,"context":{"text":"This is an house","offset":8,"length":2},"sentence":"This is an house","type":{"typeName":"Other"},"rule":{"id":"EN_A_VS_AN","description":"Use of 'a' vs. 'an'","issueType":"misspelling","urls":[{"value":"https://languagetool.org/insights/post/indefinite-articles/"}],"category":{"id":"MISC","name":"Miscellaneous"},"isPremium":false},"ignoreForIncompleteSentence":false,"contextForSureMatch":1}],"sentenceRanges":[[0,16]]}
```


**Without user and apiKey, languagetool.org**  :heavy_check_mark: 

`curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' -d "text=This%20is%20an%20house" -d "language=en-US" "https://api.languagetool.org/v2/check"`

```json
{"software":{"name":"LanguageTool","version":"6.1-SNAPSHOT","buildDate":"2023-01-23 19:23:21 +0000","apiVersion":1,"premium":true,"premiumHint":"You might be missing errors only the Premium version can find. Contact us at support<at>languagetoolplus.com.","status":""},"warnings":{"incompleteResults":false},"language":{"name":"English (US)","code":"en-US","detectedLanguage":{"name":"English (US)","code":"en-US","confidence":0.528,"source":"ngram"}},"matches":[{"message":"Use “a” instead of ‘an’ if the following word doesn’t start with a vowel sound, e.g. ‘a sentence’, ‘a university’.","shortMessage":"Wrong article","replacements":[{"value":"a"}],"offset":8,"length":2,"context":{"text":"This is an house","offset":8,"length":2},"sentence":"This is an house","type":{"typeName":"Other"},"rule":{"id":"EN_A_VS_AN","description":"Use of 'a' vs. 'an'","issueType":"misspelling","urls":[{"value":"https://languagetool.org/insights/post/indefinite-articles/"}],"category":{"id":"MISC","name":"Miscellaneous"},"isPremium":false},"ignoreForIncompleteSentence":false,"contextForSureMatch":1}],"sentenceRanges":[[0,16]]}
```

**With user and apiKey, languagetool.org** :no_entry_sign: 

`curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' -d "text=This%20is%20an%20house" -d "language=en-US" -d"username=xxx&apiKey=xxx" "https://api.languagetool.org/v2/check"`

```
Error: Credentials provided, but server isn't configured to support this.
```

I guess it will be more safe to ask them first.

**Comment by nathanlesage** [comment]
Thank you very much for double-checking and helping out. I'll send them a quick message, and then implement the change accordingly.

**Comment by nathanlesage** [comment]
So, Premium authentication should now work. Please keep me in the loop regarding the proxy!

**Comment by UFOMelkor** [comment]
So, finally found some time to tackle this.

Behind a proxy, all requests do still not work. No error is thrown, but in the Toolbar it looks like this.

![Language Tool: (offline)](https://user-images.githubusercontent.com/571106/229289062-633a6d07-8cc1-4993-a370-01cf21741eed.png)

In the logs, the following message appears:

```
[14:30:04] [Application] Error running LanguageTool: connect ETIMEDOUT 138.201.94.34:443
RequestError: connect ETIMEDOUT 138.201.94.34:443
[…]
```

It does not just affect LanguageTool, but also the check for updates.

When looking into `got`, it appears to me that it does not support proxies out of the box nor does it allow configuring them without additional packages. But there is a [section in the docs about proxies](https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying). There are some packages, which might resolve the issue. I've tested `hpagent` and `global-agent` behind a proxy and both worked for me.
In the end, `global-agent` looks more promising for me, as it can be configured with environment variables, and it can be configured globally instead of tackling every request.
