### ISSUE TITLE
Strange list indentation behaviour from the second line in beta

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#4309]
### Description

Text was indented from the second line of a numbered/unordered list, which doesn't look consistent with the text from the first line. This happened randomly.

![image](https://user-images.githubusercontent.com/37974764/235983949-2dd8bbcf-46c0-4ac8-b41f-49a14d757f0b.png)

### Reproducing

See above.

### Zettlr Version

Beta (if applicable)

### Specify version

Beta 4

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSUSE MicroOS

**Comment by nathanlesage** [comment]
This has been fixed in the most recent beta!

**Comment by sith-on-mars** [comment]
It's not fixed for me on beta 5 unfortunately, as the strange behaviour still happened randomly. Can you please reopen it?

**Comment by sith-on-mars** [comment]
It's also not fixed in nightly.
