### ISSUE TITLE
[3.1.0-beta.1] Can't open files in file manager with mouse click

### ISSUE THREAD

**Issue by tafli** [Zettlr/Zettlr#5060]
### Description

With v3.1.0-beta.1 I can't open any files in my folders by simple clicking on them.

* Workaround with right click and open in new tab works.
* Selecting folders with mouse click works

Installing latest stable version 3.0.5 does work as expected.

### Reproducing

* Install v3.1.0-beta.1 on macOS 14.4
* Open Zettlr
* Try to open a file with mouse click

### Zettlr Version

Beta (if applicable)

### Specify version

3.1.0-beta.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Sonoma 14.4

**Comment by ailintom** [comment]
In my case (Windows 11, 3.1.0-beta and 3.1.0-beta.1), Zettlr often opens a wrong file when clicking on a file in the file list, not the file I click on.

**Comment by nathanlesage** [comment]
This has been fixed in the meantime, please download the nightly from today until beta.2 is released

**Comment by tafli** [comment]
Thanks for your reply, @nathanlesage. Unfortunately, the current nightly does not solve the issue.

**Comment by ailintom** [comment]
@nathanlesage whereas my issue is mostly solved in today's nightly, one unexpected aspect of behaviour remain. In thin mode in a long list of files when you click on a file, the list of files scrolls by itself unexpectedly. This does not happen in the expanded or combined mode.

**Comment by tafli** [comment]
Good point, @ailintom. I didn't test the different display modes, as I usually work with the thin mode. However, the behavior is the same in all three modes as described above.

**Comment by nathanlesage** [comment]
The scrolling is intentional when a file is out of view. @tafli Could you create a quick screen cap to demonstrate the issue?

Also, it may help to clear the FSAL cache first from the help menu

**Comment by tafli** [comment]
@nathanlesage: Sure, find attached a short screencast:

https://github.com/Zettlr/Zettlr/assets/15720039/fdc31406-88b9-4ac4-acd4-762c219a72d5

**Comment by tafli** [comment]
Another possible issue found is, that the shortcut CMD-N does not seem to create a new file ...

**Comment by nathanlesage** [comment]
@tafli This is a different bug. Does clicking on other parts of the tile work, not just the name? Please check this, then open a new issue.

**Comment by tafli** [comment]
Follow up created #5065
