### ISSUE TITLE
[3.1.0-beta.1] [macOS] Export doesn't work

### ISSUE THREAD

**Issue by obitwrite** [Zettlr/Zettlr#5076]
### Description

The export option doesn't work in Zettlr 3.1.0-beta.1.

### Reproducing

* Create a new file, save
* Write something
* Click the export button in the Top Bar or via File > Export
* Tick either current / select directory, doesn't matter
* Click export button
* Result: nothing happens

Update: I got it to work sometimes. See comment below.

### Zettlr Version

Beta (if applicable)

### Specify version

3.1.0-beta.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ventura

**Comment by obitwrite** [comment]
I believe this might be related to the File Manager issues #5074 and #5065 

Somehow I managed to get the export to work sometimes, through some clicking on the File Manager window and creating some additional new files. It's hard to reproduce how I got it to work, it's not consistent. But for me the export remains broken in the beta.

**Comment by nathanlesage** [comment]
I can't reproduce this, at least on the most recent develop branch; same with issue #5065; at least for me the issues are fixed.

Does performing an FSAL cache reset fix the issue maybe?

**Comment by obitwrite** [comment]
Just tried clearing the FSAL cache, and also tried to downgrade and upgrade again.

Steps:
* On first startup of Zettlr I could not click anything in the File Manager, export didn't work.
* Cleared the FSAL cache, Zettlr restarted.
* After Zettlr restart, both File Manager and Export are still unresponsive (exactly the same as the screen capture in #5065).
* After that I downgraded to Zettlr 3.0.3 and both File Manager and Export work again.
* Updated again to 3.1.0-beta.1 and File Manager and Export are both unresponsive.

**Comment by obitwrite** [comment]
If I understand your test scenario's correctly @nathanlesage - both of them work. See steps and results below.

I also retested my original scenario that failed. That one still fails.

So, the bug reproduction variables seem to be:
* It is a new file that was just created AND
* The file is NOT saved in a location that is opened as a Workspace (i.e. it is saved in a 'random' location, but one that Zettlr has access to because it is allowed through macOS's Privacy and Security settings)

Steps scenario 1:
* Open Zettlr fresh, close all open files (both from Workspaces and random locations)
* Restart Zettlr (right-click Dock, close Zettlr, open)
* Right-click a file in File Manager, open in new tab (File Manager left click is unresponsive, see #5065)
* Existing file from workplace opens in new tab
* Click export, select either of the 3 options, export
* Result: works

Steps scenario 2:
* Open Zettlr fresh, close all open files (both from Workspaces and random locations)
* Restart Zettlr (right-click Dock, close Zettlr, open)
* Go to File > Open, open a file not in a Workspace
* Existing file from random locations opens in new tab
* Click export, select either of the 3 options, export
* Result: works

Steps scenario 3 (original failed scenario retest):
* Open Zettlr fresh, close all open files (both from Workspaces and random locations)
* Restart Zettlr (right-click Dock, close Zettlr, open)
* File > New file > markdown (or command+N)
* Type something
* Save file in random location
* Click export, select either of the 3 options, export
* Result: does not work.
* Log Viewer says:
[Export] Could not run exporter: No source files were given. Arguments provided:
profile: {"name":"Simple PDF.yaml","reader":"markdown","writer":"simple-pdf","isInvalid":false}
exportTo: cwd
file: (here it shows the path to the folder and .md file)

**Comment by obitwrite** [comment]
An update @nathanlesage – restested scenario 3 from the post above that consistently failed in beta.1. It seems fixed in beta.2. File manager still unresponsive / the same though.
