### ISSUE TITLE
Table: cannot save changes

### ISSUE THREAD

**Issue by DutchPete** [Zettlr/Zettlr#5666]
### Description

When I edit a table, then do CTRL+S, the vague icon at the top does not turn green but remains red. Therefore, when I close Zettlr and reopen it, the edits I did are not there anymore.

### Reproducing

- Create a table
- add data to a cell
- CTRL+S

### Zettlr version

3.4.3

### Installation Method

Other (please specify below)

### Installation Method (Other)

AppImage

### Your Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

EndeavourOS

**Comment by kyaso** [comment]
The table editor is undergoing a massive rewrite at the moment, which should fix the issues: https://github.com/Zettlr/Zettlr/pull/5243

**Comment by DutchPete** [comment]
> The table editor is undergoing a massive rewrite at the moment, which should fix the issues: https://github.com/Zettlr/Zettlr/pull/5243

I just looked at that page, it is very impressive indeed. Many thanks.

**Comment by hittjwX** [comment]
(Zettlr 3.4.4) After spending a bit of time editing a table, I learn it still doesn't save. My preference setting is to save immediately. I'm on Windows 10. Frustrating.

**Comment by hittjwX** [comment]
(Zettlr 3.6.0) I updated. Text is saving outside the table, but not in the table. And when I do a File --> Save, it scrambles the table. 

<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/a91075e8-09b6-4e41-9207-45a7d6a66990" />

However, it did save it. But if I keep editing it in Zettlr then things get worse on the screen. Then, after a while, it won't save anymore.

**Comment by nathanlesage** [comment]
Don't hesitate: I wanted to push Zettlr 3.6 with the changes in the changelog, so that I can now finally merge the overhauled table editor and push that to beta. I'll try to be quick.

**Comment by hittjwX** [comment]
Don't rush a release. I'll be happy to test anything specific when it releases.

**Comment by nathanlesage** [comment]
The PR has now been merged, and will be included in tomorrow's nightly. Once early testers report that it works mostly bug-free, we will start a beta phase and then proceed to release this feature in stable!
