### ISSUE TITLE
All windows flash white when first opened

### ISSUE THREAD

**Issue by tildagail** [Zettlr/Zettlr#5809]
### Description

When opening the app or any popup windows (e.g. preferences, about, check for updates), the window briefly flashes bright white before showing its contents. I need dark mode for accessibility reasons, and the white flash makes the app extremely difficult to use.

Note: the white flash is most noticeable in dark mode, but happens with light mode as well. 

### Reproducing

Open the app or any window that's part of the app (e.g. Preferences, About, Check for updates).

### Zettlr version

3.5.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Xubuntu 20.04 and 22.04

### Additional Information

This same white flash also occurs in other Electron apps - there's an example in this article: [Electron white screen app startup](https://www.christianengvall.se/electron-white-screen-app-startup/). The suggested fix is to either set a background colour when a new BrowserWindow is drawn, or to use a 'ready to show' event to only show the window after the contents are drawn. There's a detailed explanation of how to do this in the [BrowserWindow page of the Electron documentation](https://www.electronjs.org/docs/latest/api/browser-window/#showing-window-gracefully).

**Comment by nathanlesage** [comment]
I just double checked: I dutifully already only show windows once they're ready to show. There are two other possibilities: firstly there was a bug that I fixed I think on Monday. Please feel free to test out the current nightly, and check if it persists. If it does, I have a second idea of alternating the initial background colors based on settings.

**Comment by tildagail** [comment]
The issue is still present in the nightly build (Mon July 7). 

Overall I'm really happy to have found Zettlr. I'm doing some novel-writing in it at the moment and it seems to be doing everything I want. I had what I thought was a small, simple list of requirements (file + folder wordcount, edit two files side by side, and open files without having to move them into a special app folder) and everything else I've tried, I was having to compromise on at least one of those things.

**Comment by nathanlesage** [comment]
Roger, I'll move this on the roadmap. It SHOULD be a very simple fix!

**Comment by nathanlesage** [comment]
Please see attached fix. It will be included in next week's nightly release. It should remove the white flicker you describe!
